"""MVP schema with tenant isolation and monitoring history

Revision ID: 55463d3f0b18
Revises: 
Create Date: 2026-09-09 08:34:20.192696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55463d3f0b18'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=150), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas')),
    sa.UniqueConstraint('cnpj', name=op.f('uq_empresas_cnpj'))
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_attempts'))
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_login_attempts_key'), ['key'], unique=False)

    op.create_table('recomendacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regra', sa.String(length=50), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('acao', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recomendacoes')),
    sa.UniqueConstraint('codigo', name=op.f('uq_recomendacoes_codigo'))
    )
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('localizacao', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('ultima_coleta', sa.DateTime(), nullable=True),
    sa.Column('latencia_ms', sa.Float(), nullable=True),
    sa.Column('perda_pacotes_pct', sa.Float(), nullable=True),
    sa.Column('falhas_consecutivas', sa.Integer(), nullable=False),
    sa.Column('sucessos_consecutivos', sa.Integer(), nullable=False),
    sa.Column('arquivado_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('erro_coleta', sa.String(length=500), nullable=True),
    sa.Column('lease_owner', sa.String(length=64), nullable=True),
    sa.Column('lease_until', sa.DateTime(), nullable=True),
    sa.Column('proxima_coleta', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IS NULL OR status IN ('ONLINE','INSTAVEL','OFFLINE')", name=op.f('ck_dispositivos_status')),
    sa.CheckConstraint('falhas_consecutivas >= 0 AND sucessos_consecutivos >= 0', name=op.f('ck_dispositivos_counters')),
    sa.CheckConstraint('latencia_ms IS NULL OR latencia_ms >= 0', name=op.f('ck_dispositivos_latencia')),
    sa.CheckConstraint('perda_pacotes_pct IS NULL OR perda_pacotes_pct BETWEEN 0 AND 100', name=op.f('ck_dispositivos_perda')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_dispositivos_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispositivos'))
    )
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispositivos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispositivos_proxima_coleta'), ['proxima_coleta'], unique=False)
        batch_op.create_index('uq_dispositivo_ip_ativo', ['empresa_id', 'ip'], unique=True, sqlite_where=sa.text('arquivado_em IS NULL'), postgresql_where=sa.text('arquivado_em IS NULL'))

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=512), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criada_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint("papel IN ('ADMIN','TECNICO')", name=op.f('ck_usuarios_papel')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_usuarios_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('email', name=op.f('uq_usuarios_email'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('auth_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_auth_sessions_usuario_id_usuarios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_auth_sessions_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('falhas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fim', sa.DateTime(), nullable=True),
    sa.Column('ultima_observacao', sa.DateTime(), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=False),
    sa.Column('severidade', sa.String(length=10), nullable=False),
    sa.Column('justificativa', sa.JSON(), nullable=False),
    sa.Column('encerramento', sa.String(length=30), nullable=True),
    sa.CheckConstraint("(estado='ABERTA' AND fim IS NULL) OR (estado='ENCERRADA' AND fim IS NOT NULL)", name=op.f('ck_falhas_ciclo')),
    sa.CheckConstraint("estado IN ('ABERTA','ENCERRADA')", name=op.f('ck_falhas_estado')),
    sa.CheckConstraint("severidade IN ('BAIXA','MEDIA','ALTA','CRITICA')", name=op.f('ck_falhas_severidade')),
    sa.CheckConstraint("tipo IN ('INSTABILIDADE','INDISPONIBILIDADE')", name=op.f('ck_falhas_tipo')),
    sa.CheckConstraint('fim IS NULL OR fim >= inicio', name=op.f('ck_falhas_datas')),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], name=op.f('fk_falhas_dispositivo_id_dispositivos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_falhas'))
    )
    with op.batch_alter_table('falhas', schema=None) as batch_op:
        batch_op.create_index('ix_falhas_dispositivo_inicio', ['dispositivo_id', 'inicio'], unique=False)
        batch_op.create_index('uq_falha_aberta_dispositivo', ['dispositivo_id'], unique=True, sqlite_where=sa.text("estado = 'ABERTA'"), postgresql_where=sa.text("estado = 'ABERTA'"))

    op.create_table('metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('coletada_em', sa.DateTime(), nullable=False),
    sa.Column('respondeu', sa.Boolean(), nullable=False),
    sa.Column('latencia_ms', sa.Float(), nullable=True),
    sa.Column('pacotes_enviados', sa.Integer(), nullable=False),
    sa.Column('pacotes_recebidos', sa.Integer(), nullable=False),
    sa.Column('perda_pacotes_pct', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('ONLINE','INSTAVEL','OFFLINE')", name=op.f('ck_metricas_status')),
    sa.CheckConstraint('latencia_ms IS NULL OR latencia_ms >= 0', name=op.f('ck_metricas_latencia')),
    sa.CheckConstraint('pacotes_enviados > 0 AND pacotes_recebidos >= 0 AND pacotes_recebidos <= pacotes_enviados', name=op.f('ck_metricas_pacotes')),
    sa.CheckConstraint('perda_pacotes_pct BETWEEN 0 AND 100', name=op.f('ck_metricas_perda')),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['dispositivos.id'], name=op.f('fk_metricas_dispositivo_id_dispositivos'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metricas'))
    )
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.create_index('ix_metricas_dispositivo_data', ['dispositivo_id', 'coletada_em'], unique=False)

    op.create_table('diagnosticos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('falha_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('causas', sa.JSON(), nullable=False),
    sa.Column('evidencias', sa.JSON(), nullable=False),
    sa.Column('estado', sa.String(length=30), nullable=False),
    sa.Column('analisado_em', sa.DateTime(), nullable=False),
    sa.Column('versao_regras', sa.String(length=20), nullable=False),
    sa.CheckConstraint("estado IN ('DISPONIVEL','EVIDENCIA_INSUFICIENTE')", name=op.f('ck_diagnosticos_estado')),
    sa.ForeignKeyConstraint(['falha_id'], ['falhas.id'], name=op.f('fk_diagnosticos_falha_id_falhas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diagnosticos')),
    sa.UniqueConstraint('falha_id', name=op.f('uq_diagnosticos_falha_id'))
    )
    op.create_table('impactos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('falha_id', sa.Integer(), nullable=False),
    sa.Column('usuarios_afetados', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.CheckConstraint('usuarios_afetados IS NULL OR usuarios_afetados >= 0', name=op.f('ck_impactos_usuarios')),
    sa.ForeignKeyConstraint(['falha_id'], ['falhas.id'], name=op.f('fk_impactos_falha_id_falhas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_impactos')),
    sa.UniqueConstraint('falha_id', name=op.f('uq_impactos_falha_id'))
    )
    op.create_table('diagnostico_recomendacoes',
    sa.Column('diagnostico_id', sa.Integer(), nullable=False),
    sa.Column('recomendacao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diagnostico_id'], ['diagnosticos.id'], name=op.f('fk_diagnostico_recomendacoes_diagnostico_id_diagnosticos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recomendacao_id'], ['recomendacoes.id'], name=op.f('fk_diagnostico_recomendacoes_recomendacao_id_recomendacoes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('diagnostico_id', 'recomendacao_id', name=op.f('pk_diagnostico_recomendacoes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostico_recomendacoes')
    op.drop_table('impactos')
    op.drop_table('diagnosticos')
    with op.batch_alter_table('metricas', schema=None) as batch_op:
        batch_op.drop_index('ix_metricas_dispositivo_data')

    op.drop_table('metricas')
    with op.batch_alter_table('falhas', schema=None) as batch_op:
        batch_op.drop_index('uq_falha_aberta_dispositivo', sqlite_where=sa.text("estado = 'ABERTA'"), postgresql_where=sa.text("estado = 'ABERTA'"))
        batch_op.drop_index('ix_falhas_dispositivo_inicio')

    op.drop_table('falhas')
    with op.batch_alter_table('auth_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_sessions_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_auth_sessions_expires_at'))

    op.drop_table('auth_sessions')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))

    op.drop_table('usuarios')
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.drop_index('uq_dispositivo_ip_ativo', sqlite_where=sa.text('arquivado_em IS NULL'), postgresql_where=sa.text('arquivado_em IS NULL'))
        batch_op.drop_index(batch_op.f('ix_dispositivos_proxima_coleta'))
        batch_op.drop_index(batch_op.f('ix_dispositivos_empresa_id'))

    op.drop_table('dispositivos')
    op.drop_table('recomendacoes')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_key'))
        batch_op.drop_index(batch_op.f('ix_login_attempts_created_at'))

    op.drop_table('login_attempts')
    op.drop_table('empresas')
    # ### end Alembic commands ###
